[kisara]
token = "kisara-dev@yeuoly#toor" # this token will be used to authenticate client and master
mode = "dev" # dev or prod
dns = "8.8.8.8" # container's dns server

[kisaraClient]
address = "116.205.172.203" # this address will be infered to master server, so that master could connect to this client
port = 25570
network_in = 52428800 # 50Mbps
network_out = 52428800 # 50Mbps
max_container = 80 # max container number
db_path = "db/kisara.db" # database path
network_cidrs = "172.[128-255].[0-255].0/24" # network CIDRs available for client

[kisaraServer]
address = "159.75.81.96" # for client, which master should it connect to
port = 7474

[takina]
token = "InnerCsustTakina"